global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'client'
    static_configs:
      - targets: ['client:8080']
    metrics_path: /metrics
  - job_name: 'processor-rest'
    static_configs:
      - targets: ['processor-rest:3000']
    metrics_path: /metrics
  - job_name: 'processor-grpc'
    static_configs:
      - targets: ['processor-grpc:3001']
    metrics_path: /metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
